networks:
  dev:

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    env_file:
      - ./backend/.development.env
    ports:
      - 5000:5000
    depends_on:
      - database
    networks:
      - dev

  database:
    image: postgres:17-alpine
    container_name: database
    restart: always
    env_file:
      - ./backend/.development.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - dev
volumes:
  pgdata:
