// export const TRANSLIT_MAP: Record<string, string> = {
//   а: 'a',
//   б: 'b',
//   в: 'v',
//   г: 'g',
//   д: 'd',
//   е: 'e',
//   ё: 'yo',
//   ж: 'zh',
//   з: 'z',
//   и: 'i',
//   й: 'y',
//   к: 'k',
//   л: 'l',
//   м: 'm',
//   н: 'n',
//   о: 'o',
//   п: 'p',
//   р: 'r',
//   с: 's',
//   т: 't',
//   у: 'u',
//   ф: 'f',
//   х: 'h',
//   ц: 'ts',
//   ч: 'ch',
//   ш: 'sh',
//   щ: 'sch',
//   ъ: '',
//   ы: 'y',
//   ь: '',
//   э: 'e',
//   ю: 'yu',
//   я: 'ya',
// };

// export const REVERSE_TRANSLIT_MAP = Object.fromEntries(
//   Object.entries(TRANSLIT_MAP).map(([rus, eng]) => [eng, rus]),
// );
